### ISSUE TITLE
Issues Tracker link doesnt work

### ISSUE THREAD

**Issue by rtpHarry** [madskristensen/ExtensionGallery#11]
Eg:
- http://vsixgallery.com/extension/e6e2a48e-387d-4af2-9072-86a5276da6d4/

It's being bound urlencoded:

```
<a href="https%3a%2f%2fgithub.com%2fligershark%2fside-waffle%2fissues/"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Issue Tracker</a>
```

**Comment by rtpHarry** [comment]
Not sure why this one is occurring. 

On my local build based on beta4 it isn't exhibiting this behaviour, the link is a normal, non-encoded, clickable link.

**Comment by madskristensen** [comment]
Fixed
