### ISSUE TITLE
Notification for autoupdates?

### ISSUE THREAD

**Issue by codewithtyler** [madskristensen/ExtensionGallery#24]
I'm running Visual Studio 2015 Community. By default VS routinely checks to see if all my extensions are up to date. Is there anything currently in place that will allow us to do this for the VSIX Gallery?

**Comment by madskristensen** [comment]
Yes, when you subscribe to the feed as described here http://vsixgallery.com/guide/feed/ then Visual Studio 2015 will automatically check for updates from that feed

**Comment by codewithtyler** [comment]
Great, thanks!
