### ISSUE TITLE
Remove orphan extensions

### ISSUE THREAD

**Issue by ErikEJ** [madskristensen/ExtensionGallery#31]
The release of https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VSIXGallery-nightlybuilds has exposed on number of "orphaned" extensions of mine on vsixgallery.com - any way to have them removed?

**Comment by madskristensen** [comment]
Which ones should be removed? I need either the id or the url

**Comment by ErikEJ** [comment]
http://vsixgallery.com/extension/45521019-e4c7-480c-8ea8-fc4a2c6f50aa 
http://vsixgallery.com/extension/SSMSToolbox.ErikEJ.d6c77c32-fe4b-4f6d-ad5d-f7b755212760 
http://vsixgallery.com/extension/SQLCeToolbox.ErikEJ.41521019-e4c7-480c-8ea8-fc4a2c6f50aa 

TIA!

**Comment by madskristensen** [comment]
Done

**Comment by ErikEJ** [comment]
Thanks, Mads, beers are on me next time I am on Campus

**Comment by madskristensen** [comment]
Sounds good :)
