### ISSUE TITLE
Remove duplicate ApiPort extensions

### ISSUE THREAD

**Issue by twsouthwick** [madskristensen/ExtensionGallery#35]
My team started pushing ApiPort extension to the gallery a year ago, and I noticed today that there are a couple of duplicates from when we were getting things set up. They are:

- http://vsixgallery.com/extension/00000000-0000-0000-0000-000000000000/
- http://vsixgallery.com/extension/05b3d9f1-6699-4f10-a9e4-da2ed1248523/

Can these be removed?

**Comment by madskristensen** [comment]
They have now been removed

**Comment by twsouthwick** [comment]
Thanks!
