### ISSUE TITLE
www subdomain not set up

### ISSUE THREAD

**Issue by rtpHarry** [madskristensen/ExtensionGallery#7]
If you try to access the website using http://www.vsixgallery.com/ you get an error, it only works with the non-www version http://vsixgallery.com/

**Comment by yannduran** [comment]
This works now, so the issue can be closed.

**Comment by rtpHarry** [comment]
![image](https://user-images.githubusercontent.com/1038062/50998785-7229f580-1520-11e9-9eaa-9299b7fcf559.png)

Hmm, I'm not seeing that for me trying directly or using a tool (https://httpstatus.io/)
