### ISSUE TITLE
site isn't correctly deploying from github?

### ISSUE THREAD

**Issue by rtpHarry** [madskristensen/ExtensionGallery#8]
I was just watching your recent side projects video on Web Camps TV and spotted the "choosing the rigth feed" typo.

I came here to do a quick pull request but:
1. On this github repo the typo is fixed
2. On the website it still showing the typo: http://vsixgallery.com/guide/feed/

**Comment by rtpHarry** [comment]
I had a bit more of a look around and found a cache file, pull request #9 should fix this.

**Comment by rtpHarry** [comment]
@madskristensen Just checked and the website is still displaying the typo - do you have to manually redeploy this site?

**Comment by madskristensen** [comment]
Yes, I have not set up automatic Kudu deployment for the site yet. I'm travelling for the next couple of weeks so it might take a little while before I can update it. Thanks for the PRs!!

**Comment by madskristensen** [comment]
Fixed
